---
- hosts: linux
  gather_facts: true
  tasks:
    - debug:
        var: hostvars.keys()

    - set_stats:
        data:
          output: "{{ hostvars }}" 
          "{{ inventory_hoatname_short }}": "{{ hostvars[inventory_hostname_short] }}"
